stages:
  - lint
  - test
  - deploy

flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install flake8
  script:
    - flake8 --exclude=./cityair_api/__init__.py -v --per-file-ignores='cityair_api/__init__.py:F401 setup.py:E121'

pytest:
  stage: test
  image: python:3.7-alpine
  before_script:
    - pip install pytest
  script:
    - pytest
    - echo $CITYAIR_TOKEN
    - echo $PYPI_USER

pypi:
  stage: deploy
  only:
    - master
  image: python:3.7-alpine
  before_script:
    - pip install twine
  script:
    - python setup.py sdist
    - twine upload dist/* -u $PYPI_USER -p $PYPI_PASSWORD




