stages:
  - lint
  - test
  - deploy



flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8 --exclude=./cityair_api/__init__.py -v --per-file-ignores='cityair_api/__init__.py:F401 setup.py:E121'


pytest:
  stage: test
  image: python:3.7
  tags:
    - docker
  services:
    - docker
  before_script:
    - docker-compose -f local.yml build
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run django pytest

# pip install -U
# copy service file
# enable
# daemon-reload
# systemctl restart
